[package]
name = "pesto-term"
version = "0.1.0"
edition = "2024"

[dependencies]
norcina = { path = "../norcina" }
pesto-core = { path = "../pesto-core" }
ratatui = "0.29.0"
crossterm.workspace = true
color-eyre.workspace = true
tui-big-text = "0.7.1"
