[package]
name = "pesto-term"
version = "0.1.0"
edition = "2024"

[dependencies]
norcina = { path = "../norcina" }
pesto-core = { path = "../pesto-core" }
crossterm.workspace = true
color-eyre.workspace = true
rand.workspace = true
ratatui = "0.29.0"
tui-big-text = "0.7.1"
device_query = "4.0.0"
